# Generated by Django 5.1.1 on 2024-11-30 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_brands_tovars_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='cv_doce',
        ),
        migrations.RemoveField(
            model_name='users',
            name='nomer_cart',
        ),
    ]
