# Generated by Django 5.1.1 on 2024-12-11 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_alter_usercreditcart_cvcode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercreditcart',
            old_name='nomercart',
            new_name='nomer',
        ),
        migrations.AlterField(
            model_name='usercreditcart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first.users'),
        ),
    ]
