# Generated by Django 5.1.1 on 2024-12-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0008_remove_usercreditcart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tovars',
            name='brands',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tovars',
            name='naimenovanie',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tovars',
            name='price',
            field=models.IntegerField(),
        ),
    ]
